using Pkg; Pkg.activate(ENV["JWfSim"])

begin
	using PlutoUI
	using CSV
	using DataFrames
	using Images
	using Colors
	using Clustering
	using Plots
	using Printf
	using InteractiveUtils
	using Statistics
	using StatsBase
	using StatsPlots
	using Distributions
	using Unitful 
	using UnitfulEquivalences 
	using PhysicalConstants
	using PoissonRandom
	using ImageFiltering
	using ImageSegmentation

end

import Unitful:
    nm, μm, mm, cm, m, km,
    mg, g, kg,
    ps, ns, μs, ms, s, minute, hr, d, yr, Hz, kHz, MHz, GHz,
    eV,
    μJ, mJ, J,
	μW, mW, W,
    A, N, mol, mmol, V, L, M


function ingredients(path::String)
    # this is from the Julia source code (evalfile in base/loading.jl)
    # but with the modification that it returns the module instead of the last object
    name = Symbol(basename(path))
    m = Module(name)
    Core.eval(m,
        Expr(:toplevel,
                :(eval(x) = $(Expr(:core, :eval))($name, x)),
                :(include(x) = $(Expr(:top, :include))($name, x)),
                :(include(mapexpr::Function, x) = $(Expr(:top, :include))(mapexpr, $name, x)),
                :(include($path))))
    m
end

jwf = ingredients("../src/jwfsim.jl")

PlutoUI.TableOfContents(title="Notebook title", indent=true)

md"""
### Waist fills the focusing lens

$w_0' = \frac{\lambda}{\pi w_0} f$

$z' = f$
"""
load("gaussianBeamFillingLens2.png")

jwf.jwfsim.w0f(325*nm, 3.9*mm, 5.0*mm)

md"""
### Wide field setup

1. Use a focusing length to focus laser into a point at f'
2. Plase MO at a distance $f_{MO}$ to achieve a paralell beam of diameter $d_0$

"""

md"""
### Wide field setup

$w_0 = \frac{2\lambda f}{\pi D}$
$d_0 = 2 w_0' = \frac{1.22\lambda f_{MO}}{w_0}$
$w_0' =\frac{1.22\pi D}{4} \frac{f_{MO}}{f'}$
$w_0' =\frac{1.05\pi D}{4} \frac{f_{MO}}{f'} {\rm (~FWHM)}$
"""



md"""
## TOPATU WFS

- Laser: $\lambda=405$ nm; Variable power between 10 mW and 100 mW. 
- Setup 
$f'=75-200 ~{\rm mm}$
$d_{beam} = 0.94~{\rm mm}$ 
$D = G \times d_{beam}$ where G ϵ[2,8] 
 
 - For MUE31900 100x/0.6NA, which generates the widefield, $f_{MO}$ is 3mm

- MUE21200 20x/0.4NA, $f_{MO}$ is 10mm

- MUE20501 50x/0.55NA, $f_{MO}$ is 4mm

- The default value of f' is 150 mm. 
"""

md" set laser wavelength in nm $(@bind ll NumberField(10.0^2:10.0^3; default=405.0))"
md" set laser power in mW $(@bind lp NumberField(10.0^1:10.0^3; default=10.0))"
lsrwf = jwf.jwfsim.CLaser(ll*nm, lp*mW)

md" set laser diameter in nm $(@bind ld NumberField(0.1:0.1:5.0; default=0.9))"
md"""
The laser is initially a gaussian beam of waist d0/2
"""
d0 = ld*mm/2.0
glsrwf1 = jwf.jwfsim.GaussianLaser(lsrwf, d0)

md"""
The laser is now expanded by a factor G and focused by a lens of focal length f
"""

md" set focal length of focusing lens $(@bind fp NumberField(1.0:1.0:200.0; default=150.0))"

md""" 
The new waist at f is 
$w_0 = \frac{2\lambda f}{\pi G d_0}$
"""

ff = fp * mm
w0f = uconvert(μm, 2.0 * lsrwf.λ * ff/(π * le * d0))
uconvert(μm, jwf.jwfsim.w0f(lsrwf.λ, le * d0, ff))

md"""
Finally a paralell beam is generated by using an infinity corrected objective
"""
schema = ["MUE31900", "MUE21200", "MUE20501"]

FMO =Dict("MUE31900"=>3*mm, "MUE21200"=>10*mm, "MUE20501"=>4*mm)

md"""
- Wide field waist for selected parameters (FWHM)
- Laser wavelength = $(lsrwf.λ)
- Laser diameter = $d0
- Laser expansion factor = $le
- Fousing length f' = $ff
- Objective = $obj
- Objective fMO = $(FMO[obj])
- w0f = $(uconvert(μm, jwf.jwfsim.w0f(lsrwf.λ, le * d0, ff)))
- w0fMO = $(uconvert(μm, jwf.jwfsim.w0wf(d0, ff, FMO[obj], le, 1.05)))
"""

w0M0 = uconvert(μm, jwf.jwfsim.w0wf(d0, ff, FMO[obj], le, 1.05))

begin

    GG = range(0,10, length=10)
    WW = [jwf.jwfsim.w0wf(d0, ff, FMO[obj], g, 1.05) for g in GG] 
    
    plot(GG,uconvert.(μm, WW), xlabel="G",ylabel="w0MO", lw =2, label="f'=$ff, obj=$obj", size=(800,400))
    end

    
